//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CHC
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public string CHC_Lat { get; set; }
        public string CHC_Long { get; set; }
        public string CHC_Name { get; set; }
        public Nullable<int> Mas_State_Fid { get; set; }
        public Nullable<int> Mas_Postcode_Fid { get; set; }
        public string CHC_Address { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
