//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mas_AssignArea
    {
        public int FId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<int> StateFid { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public Nullable<int> Mas_LeaderFid { get; set; }
        public Nullable<int> Mas_churchFId { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
