//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Calender
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<int> MAS_CHC_FID { get; set; }
        public Nullable<System.DateTime> CAL_Date { get; set; }
        public string CAL_Description { get; set; }
    }
}
