//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mas_EventVideo
    {
        public int FId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<bool> Deactivate { get; set; }
        public Nullable<int> ChurchFId { get; set; }
        public Nullable<int> LeaderFId { get; set; }
        public Nullable<int> EventFId { get; set; }
        public string VideoUrl { get; set; }
        public string AdminEvent { get; set; }
    }
}
