//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_INDVSL
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<int> StateFid { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public Nullable<int> MAS_CHC_FID { get; set; }
        public Nullable<bool> Deactivate { get; set; }
        public string IND_Name { get; set; }
        public string IND_Mob { get; set; }
        public string IND_Email { get; set; }
        public Nullable<System.DateTime> IND_DOJ { get; set; }
        public Nullable<System.DateTime> IND_DOB { get; set; }
        public string Gender { get; set; }
        public string IND_Address { get; set; }
        public string AdharNo { get; set; }
        public string NameAsAadhar { get; set; }
        public string IND_Image { get; set; }
        public string IND_ReffName { get; set; }
        public Nullable<int> Enroll_ID { get; set; }
        public string Enroll_Type { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
