//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mas_Notice
    {
        public int FId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<bool> Deactivate { get; set; }
        public Nullable<int> LeaderFId { get; set; }
        public Nullable<int> CurchId { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string NoticeSubject { get; set; }
        public string NoticeDescription { get; set; }
        public Nullable<System.DateTime> NoticeDateValid { get; set; }
        public Nullable<bool> NoticeViews { get; set; }
        public Nullable<bool> Meal_Attandence { get; set; }
        public string NoticeCreateBy { get; set; }
    }
}
