//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mas_Enquiry
    {
        public int FId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<bool> Deactivate { get; set; }
        public Nullable<int> CurchId { get; set; }
        public Nullable<int> MemberFId { get; set; }
        public Nullable<int> LeaderFId { get; set; }
        public string Subject { get; set; }
        public string Enquiry { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public Nullable<System.DateTime> ResponsedDate { get; set; }
        public string Respons { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> LeaderResponseStatus { get; set; }
    }
}
