//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mas_ReadView
    {
        public int FId { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<int> NoticeFId { get; set; }
        public Nullable<int> MemberFId { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Like { get; set; }
    }
}
