//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_LEADER
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<int> StateFid { get; set; }
        public string CityName { get; set; }
        public string ChurchArea { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> MAS_CHC_FID { get; set; }
        public string Lead_Name { get; set; }
        public string Lead_Mob { get; set; }
        public string Lead_EmailID { get; set; }
        public string Gender { get; set; }
        public string Lead_Add { get; set; }
        public Nullable<System.DateTime> Lead_DOJ { get; set; }
        public Nullable<System.DateTime> Lead_DOB { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Position { get; set; }
    }
}
