//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_PrayerReq
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string Mac_ID { get; set; }
        public string Mac_IP { get; set; }
        public Nullable<bool> Deactivate { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> MAS_CHC_FID { get; set; }
        public Nullable<int> Req_ID { get; set; }
        public Nullable<System.DateTime> Req_Date { get; set; }
        public Nullable<bool> Req_Status { get; set; }
        public string PrayerRemark { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    }
}
