//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAttendance
    {
        public int FID { get; set; }
        public Nullable<System.DateTime> FDate { get; set; }
        public string MacID { get; set; }
        public string MacIP { get; set; }
        public Nullable<int> Mas_ChurchFid { get; set; }
        public Nullable<int> MemberFid { get; set; }
        public Nullable<int> NoticeFid { get; set; }
        public Nullable<int> NoOFAdult { get; set; }
        public Nullable<int> NoOfChild { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
