//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Church.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CHC_NewEntities : DbContext
    {
        public CHC_NewEntities()
            : base("name=CHC_NewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MAS_ACTIVITY_I> MAS_ACTIVITY_I { get; set; }
        public virtual DbSet<MAS_Calender> MAS_Calender { get; set; }
        public virtual DbSet<MAS_UID> MAS_UID { get; set; }
        public virtual DbSet<MAS_ACTIVITY_II> MAS_ACTIVITY_II { get; set; }
        public virtual DbSet<MAS_INDVFMLY> MAS_INDVFMLY { get; set; }
        public virtual DbSet<MAS_STATE> MAS_STATE { get; set; }
        public virtual DbSet<MAS_POSTCOD> MAS_POSTCOD { get; set; }
        public virtual DbSet<MAS_CHC> MAS_CHC { get; set; }
        public virtual DbSet<Mas_ReadView> Mas_ReadView { get; set; }
        public virtual DbSet<Mas_LeaderComment> Mas_LeaderComment { get; set; }
        public virtual DbSet<Mas_Donation> Mas_Donation { get; set; }
        public virtual DbSet<Mas_Enquiry> Mas_Enquiry { get; set; }
        public virtual DbSet<DocumentBaseUrl> DocumentBaseUrls { get; set; }
        public virtual DbSet<MAS_LEADER> MAS_LEADER { get; set; }
        public virtual DbSet<MAS_PrayerReq> MAS_PrayerReq { get; set; }
        public virtual DbSet<Mas_AssignArea> Mas_AssignArea { get; set; }
        public virtual DbSet<Mas_Event> Mas_Event { get; set; }
        public virtual DbSet<Mas_EventPost> Mas_EventPost { get; set; }
        public virtual DbSet<Mas_EventVideo> Mas_EventVideo { get; set; }
        public virtual DbSet<MAS_INDVSL> MAS_INDVSL { get; set; }
        public virtual DbSet<Mas_Notice> Mas_Notice { get; set; }
        public virtual DbSet<MealAttendance> MealAttendances { get; set; }
    
        public virtual ObjectResult<Sp_ListofFamilyMember_Result> Sp_ListofFamilyMember(Nullable<int> indvsl_Fid, string role)
        {
            var indvsl_FidParameter = indvsl_Fid.HasValue ?
                new ObjectParameter("Indvsl_Fid", indvsl_Fid) :
                new ObjectParameter("Indvsl_Fid", typeof(int));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ListofFamilyMember_Result>("Sp_ListofFamilyMember", indvsl_FidParameter, roleParameter);
        }
    
        public virtual ObjectResult<sp_List_INDVSLFamilyMember_Result> sp_List_INDVSLFamilyMember(Nullable<int> p_INDVSLFID, Nullable<int> p_ChurchFid)
        {
            var p_INDVSLFIDParameter = p_INDVSLFID.HasValue ?
                new ObjectParameter("p_INDVSLFID", p_INDVSLFID) :
                new ObjectParameter("p_INDVSLFID", typeof(int));
    
            var p_ChurchFidParameter = p_ChurchFid.HasValue ?
                new ObjectParameter("p_ChurchFid", p_ChurchFid) :
                new ObjectParameter("p_ChurchFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_INDVSLFamilyMember_Result>("sp_List_INDVSLFamilyMember", p_INDVSLFIDParameter, p_ChurchFidParameter);
        }
    
        public virtual ObjectResult<sp_List_MemberPendingEnquiry_Result> sp_List_MemberPendingEnquiry(Nullable<int> p_ChurhFid, Nullable<int> p_MemberFid)
        {
            var p_ChurhFidParameter = p_ChurhFid.HasValue ?
                new ObjectParameter("p_ChurhFid", p_ChurhFid) :
                new ObjectParameter("p_ChurhFid", typeof(int));
    
            var p_MemberFidParameter = p_MemberFid.HasValue ?
                new ObjectParameter("p_MemberFid", p_MemberFid) :
                new ObjectParameter("p_MemberFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_MemberPendingEnquiry_Result>("sp_List_MemberPendingEnquiry", p_ChurhFidParameter, p_MemberFidParameter);
        }
    
        public virtual ObjectResult<sp_List_Events_Result> sp_List_Events()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_Events_Result>("sp_List_Events");
        }
    
        public virtual ObjectResult<sp_List_LeaderRegistredMembersList_Result> sp_List_LeaderRegistredMembersList(Nullable<int> p_ChurchFid)
        {
            var p_ChurchFidParameter = p_ChurchFid.HasValue ?
                new ObjectParameter("p_ChurchFid", p_ChurchFid) :
                new ObjectParameter("p_ChurchFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_LeaderRegistredMembersList_Result>("sp_List_LeaderRegistredMembersList", p_ChurchFidParameter);
        }
    
        public virtual ObjectResult<sp_List_GetLeaderDetail_Result> sp_List_GetLeaderDetail(Nullable<int> p_LeaderFID, Nullable<int> p_ChurchFid)
        {
            var p_LeaderFIDParameter = p_LeaderFID.HasValue ?
                new ObjectParameter("p_LeaderFID", p_LeaderFID) :
                new ObjectParameter("p_LeaderFID", typeof(int));
    
            var p_ChurchFidParameter = p_ChurchFid.HasValue ?
                new ObjectParameter("p_ChurchFid", p_ChurchFid) :
                new ObjectParameter("p_ChurchFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_GetLeaderDetail_Result>("sp_List_GetLeaderDetail", p_LeaderFIDParameter, p_ChurchFidParameter);
        }
    
        public virtual ObjectResult<sp_List_Donation_Result> sp_List_Donation(Nullable<int> p_DonationStatus, Nullable<int> p_ChurchFid, Nullable<System.DateTime> p_FromDate, Nullable<System.DateTime> p_ToDate)
        {
            var p_DonationStatusParameter = p_DonationStatus.HasValue ?
                new ObjectParameter("p_DonationStatus", p_DonationStatus) :
                new ObjectParameter("p_DonationStatus", typeof(int));
    
            var p_ChurchFidParameter = p_ChurchFid.HasValue ?
                new ObjectParameter("p_ChurchFid", p_ChurchFid) :
                new ObjectParameter("p_ChurchFid", typeof(int));
    
            var p_FromDateParameter = p_FromDate.HasValue ?
                new ObjectParameter("p_FromDate", p_FromDate) :
                new ObjectParameter("p_FromDate", typeof(System.DateTime));
    
            var p_ToDateParameter = p_ToDate.HasValue ?
                new ObjectParameter("p_ToDate", p_ToDate) :
                new ObjectParameter("p_ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_Donation_Result>("sp_List_Donation", p_DonationStatusParameter, p_ChurchFidParameter, p_FromDateParameter, p_ToDateParameter);
        }
    
        public virtual ObjectResult<sp_List_Church_Result> sp_List_Church()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_Church_Result>("sp_List_Church");
        }
    
        public virtual ObjectResult<sp_GetMemberData_Result> sp_GetMemberData(Nullable<int> p_INDVSLFID, Nullable<int> p_ChurchFid)
        {
            var p_INDVSLFIDParameter = p_INDVSLFID.HasValue ?
                new ObjectParameter("p_INDVSLFID", p_INDVSLFID) :
                new ObjectParameter("p_INDVSLFID", typeof(int));
    
            var p_ChurchFidParameter = p_ChurchFid.HasValue ?
                new ObjectParameter("p_ChurchFid", p_ChurchFid) :
                new ObjectParameter("p_ChurchFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetMemberData_Result>("sp_GetMemberData", p_INDVSLFIDParameter, p_ChurchFidParameter);
        }
    
        public virtual ObjectResult<sp_List_ReadNotice_Result> sp_List_ReadNotice(Nullable<int> p_NoticeFId, Nullable<int> p_ChurchFid)
        {
            var p_NoticeFIdParameter = p_NoticeFId.HasValue ?
                new ObjectParameter("p_NoticeFId", p_NoticeFId) :
                new ObjectParameter("p_NoticeFId", typeof(int));
    
            var p_ChurchFidParameter = p_ChurchFid.HasValue ?
                new ObjectParameter("p_ChurchFid", p_ChurchFid) :
                new ObjectParameter("p_ChurchFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_ReadNotice_Result>("sp_List_ReadNotice", p_NoticeFIdParameter, p_ChurchFidParameter);
        }
    
        public virtual ObjectResult<PendingPrayerRequest_Result> PendingPrayerRequest(Nullable<int> p_LeaderChurchId, string p_LeaderDesignation, Nullable<int> p_LeaderFid, Nullable<int> p_StateFid)
        {
            var p_LeaderChurchIdParameter = p_LeaderChurchId.HasValue ?
                new ObjectParameter("p_LeaderChurchId", p_LeaderChurchId) :
                new ObjectParameter("p_LeaderChurchId", typeof(int));
    
            var p_LeaderDesignationParameter = p_LeaderDesignation != null ?
                new ObjectParameter("p_LeaderDesignation", p_LeaderDesignation) :
                new ObjectParameter("p_LeaderDesignation", typeof(string));
    
            var p_LeaderFidParameter = p_LeaderFid.HasValue ?
                new ObjectParameter("p_LeaderFid", p_LeaderFid) :
                new ObjectParameter("p_LeaderFid", typeof(int));
    
            var p_StateFidParameter = p_StateFid.HasValue ?
                new ObjectParameter("p_StateFid", p_StateFid) :
                new ObjectParameter("p_StateFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PendingPrayerRequest_Result>("PendingPrayerRequest", p_LeaderChurchIdParameter, p_LeaderDesignationParameter, p_LeaderFidParameter, p_StateFidParameter);
        }
    
        public virtual ObjectResult<sp_List_CurchMember_Result> sp_List_CurchMember(Nullable<int> p_ChurchID, Nullable<int> p_LeaderFid, string p_LeaderDesignation, Nullable<int> p_StateFid)
        {
            var p_ChurchIDParameter = p_ChurchID.HasValue ?
                new ObjectParameter("p_ChurchID", p_ChurchID) :
                new ObjectParameter("p_ChurchID", typeof(int));
    
            var p_LeaderFidParameter = p_LeaderFid.HasValue ?
                new ObjectParameter("p_LeaderFid", p_LeaderFid) :
                new ObjectParameter("p_LeaderFid", typeof(int));
    
            var p_LeaderDesignationParameter = p_LeaderDesignation != null ?
                new ObjectParameter("p_LeaderDesignation", p_LeaderDesignation) :
                new ObjectParameter("p_LeaderDesignation", typeof(string));
    
            var p_StateFidParameter = p_StateFid.HasValue ?
                new ObjectParameter("p_StateFid", p_StateFid) :
                new ObjectParameter("p_StateFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_CurchMember_Result>("sp_List_CurchMember", p_ChurchIDParameter, p_LeaderFidParameter, p_LeaderDesignationParameter, p_StateFidParameter);
        }
    
        public virtual ObjectResult<sp_List_Enquiry_Result> sp_List_Enquiry(Nullable<int> p_ChurhFid, string p_LeaderDesignation, Nullable<int> p_LeaderFid, Nullable<int> p_StateFid)
        {
            var p_ChurhFidParameter = p_ChurhFid.HasValue ?
                new ObjectParameter("p_ChurhFid", p_ChurhFid) :
                new ObjectParameter("p_ChurhFid", typeof(int));
    
            var p_LeaderDesignationParameter = p_LeaderDesignation != null ?
                new ObjectParameter("p_LeaderDesignation", p_LeaderDesignation) :
                new ObjectParameter("p_LeaderDesignation", typeof(string));
    
            var p_LeaderFidParameter = p_LeaderFid.HasValue ?
                new ObjectParameter("p_LeaderFid", p_LeaderFid) :
                new ObjectParameter("p_LeaderFid", typeof(int));
    
            var p_StateFidParameter = p_StateFid.HasValue ?
                new ObjectParameter("p_StateFid", p_StateFid) :
                new ObjectParameter("p_StateFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_Enquiry_Result>("sp_List_Enquiry", p_ChurhFidParameter, p_LeaderDesignationParameter, p_LeaderFidParameter, p_StateFidParameter);
        }
    
        public virtual ObjectResult<sp_List_AssignArea_Result> sp_List_AssignArea(Nullable<int> p_LeaderFid, Nullable<int> p_churchFid)
        {
            var p_LeaderFidParameter = p_LeaderFid.HasValue ?
                new ObjectParameter("p_LeaderFid", p_LeaderFid) :
                new ObjectParameter("p_LeaderFid", typeof(int));
    
            var p_churchFidParameter = p_churchFid.HasValue ?
                new ObjectParameter("p_churchFid", p_churchFid) :
                new ObjectParameter("p_churchFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_AssignArea_Result>("sp_List_AssignArea", p_LeaderFidParameter, p_churchFidParameter);
        }
    
        public virtual ObjectResult<sp_List_MealAttendance_Result> sp_List_MealAttendance(Nullable<int> p_ChurhFid, string p_LeaderDesignation, Nullable<int> p_LeaderFid, Nullable<int> p_StateFid)
        {
            var p_ChurhFidParameter = p_ChurhFid.HasValue ?
                new ObjectParameter("p_ChurhFid", p_ChurhFid) :
                new ObjectParameter("p_ChurhFid", typeof(int));
    
            var p_LeaderDesignationParameter = p_LeaderDesignation != null ?
                new ObjectParameter("p_LeaderDesignation", p_LeaderDesignation) :
                new ObjectParameter("p_LeaderDesignation", typeof(string));
    
            var p_LeaderFidParameter = p_LeaderFid.HasValue ?
                new ObjectParameter("p_LeaderFid", p_LeaderFid) :
                new ObjectParameter("p_LeaderFid", typeof(int));
    
            var p_StateFidParameter = p_StateFid.HasValue ?
                new ObjectParameter("p_StateFid", p_StateFid) :
                new ObjectParameter("p_StateFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_MealAttendance_Result>("sp_List_MealAttendance", p_ChurhFidParameter, p_LeaderDesignationParameter, p_LeaderFidParameter, p_StateFidParameter);
        }
    
        public virtual ObjectResult<sp_List_Notice_Result> sp_List_Notice(Nullable<int> p_MemberFid)
        {
            var p_MemberFidParameter = p_MemberFid.HasValue ?
                new ObjectParameter("p_MemberFid", p_MemberFid) :
                new ObjectParameter("p_MemberFid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_Notice_Result>("sp_List_Notice", p_MemberFidParameter);
        }
    
        public virtual ObjectResult<sp_List_LeaderCreate_Result> sp_List_LeaderCreate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_List_LeaderCreate_Result>("sp_List_LeaderCreate");
        }
    }
}
